---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-shared
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/network/ingress-nginx/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  dependsOn:
    - name: cert-manager-issuers
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-external
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/network/ingress-nginx/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  dependsOn:
    - name: nginx-shared
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-internal
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/cluster-0/apps/network/ingress-nginx/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  dependsOn:
    - name: nginx-shared
