apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: downloads-nas-media
  resources:
    requests:
      storage: 1Ti # Size does not matter
