---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: plex-trakt-sync
spec:
  sourcePVC: plex-trakt-sync-config
  trigger:
    schedule: "15 */8 * * *"
  restic:
    copyMethod: Snapshot
    repository: plex-trakt-sync-restic-secret
    cacheStorageClassName: local-hostpath
    cacheCapacity: 1Gi
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    pruneIntervalDays: 7
    retain:
      daily: 7
      within: 3d
