---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/downloads/plex/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
    - name: external-secrets-stores
