apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/tailscale/tailscale
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/cmd/k8s-operator/deploy
