---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
  namespace: network
spec:
  endpoints:
    - dnsName: "ingress.akramboutou.xyz"
      recordType: CNAME
      targets: ["4a96e3dd-148b-42c0-922c-6f4a6674c58f.cfargotunnel.com"]
