---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./dns-endpoint.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: cloudflared
    files:
      - ./config.yaml
generatorOptions:
  disableNameSuffixHash: true
