apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-config
  namespace: downloads
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
