---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: keycloak-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: keycloak
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: keycloak
        property: admin-password
    - secretKey: realm-name
      remoteRef:
        key: keycloak
        property: realm-name
