---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloack
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542 # gladius:external-services
        containers:
          main:
            image:
              repository: quay.io/keycloak/keycloak
              tag: 23.0.4
            env:
              KEYCLOAK_ADMIN:
                valueFrom:
                  secretKeyRef:
                    name: keycloak-secret
                    key: admin-user
              KEYCLOAK_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: keycloack-secret
                    key: admin-password
              KC_REALM_NAME:
                valueFrom:
                  secretKeyRef:
                    name: keycloak-secret
                    key: realm-name
              KC_DB: postgres
              KC_DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: "${APP}-pguser-${DB_USER}"
                    key: host
              KC_DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "${APP}-pguser-${DB_USER}"
                    key: password
            resources:
              requests:
                cpu: 20m
                memory: 512M
              limits:
                memory: 768M

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.akramboutou.xyz
        className: "nginx"
        hosts:
          - host: "${HOSTNAME}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "${HOSTNAME}"
