---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 65542 # gladius:external-services

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.32.7.7621-871adbd44@sha256:f9f77dc5e17cab9fae5ece663a64d026e3c75142b3b60bb4a52bf061957412be
            resources:
              requests:
                cpu: 100m
                memory: 9248M
              limits:
                memory: 9248M

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "192.168.0.110"
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.akramboutou.xyz
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        className: "external-nginx"
        hosts:
          - host: &host plex.akramboutou.xyz
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: plex-config
        advancedMounts:
          main:
            main:
              - path: /config
      nfs-nas-media:
        existingClaim: nas-media
        advancedMounts:
          main:
            main:
              - path: /data/nas-media
      transcode:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /transcode
