---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/network/metallb/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
---
