---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "akramboutou.xyz"
  namespace: network
spec:
  secretName: "akramboutou-xyz-tls"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "akramboutou.xyz"
  dnsNames:
    - "akramboutou.xyz"
    - "*.akramboutou.xyz"
