# https://wiki.archlinux.org/title/etckeeper
---
- name: Check supported distribution
  fail:
    msg:
      - "Unsupported distribution: {{ ansible_facts['distribution'] | lower }}"
      - This role only supports Arch Linux and Ubuntu
  when: ansible_facts['distribution'] | lower != 'archlinux' and ansible_facts['distribution'] | lower != 'ubuntu'

- name: Install etckeeper (Arch)
  ansible.builtin.package:
    name:
      - etckeeper

- name: Install etckeeper (Ubuntu)
  ansible.builtin.apt:
    name:
      - etckeeper

- name: Check /etc/.git exists
  ansible.builtin.stat:
    path: /etc/.git
  register: etc_git_result

- block:
    - name: Initialize etckeeper
      ansible.builtin.command: etckeeper init

    - name: Configure git email
      ansible.builtin.command: etckeeper vcs config user.email $HOSTNAME@home.arpa

    - name: Configure git name
      ansible.builtin.command: etckeeper vcs config user.name $HOSTNAME

    - name: Initialize etckeeper
      ansible.builtin.command: etckeeper commit "initial commit"
  when: not etc_git_result.stat.exists
