---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-cloudflared
  namespace: flux-system
spec:
  dependsOn:
    - name: externaldns-external
  path: ./kubernetes/apps/network/cloudflared/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
