---
- hosts:
    - kratos
  become: true
  roles:
    - os
    - role: upgrade
      vars:
        allow_reboot: false

- hosts:
    - kratos
  become: true
  pre_tasks:
    - name: Check supported distribution
      ansible.builtin.fail:
        msg:
          - "Unsupported distribution: {{ ansible_facts['distribution'] | lower }}"
          - This role only supports Arch Linux and Ubuntu
      when: ansible_facts['distribution'] | lower != 'archlinux' and ansible_facts['distribution'] | lower != 'ubuntu'

    - name: Install packages (Arch Linux)
      ansible.builtin.package:
        state: latest
        name:
          - base
          - dhcpcd
          - dosfstools
          - efibootmgr
          - git
          - grub
          - vim
          - linux
          - linux-headers
          - linux-firmware
          - mtools
          - nano
          - os-prober
          - btop
          - curl
          - intel-ucode
          - mesa
          - networkmanager
          - net-tools
          - openssh
          - reflector
          - rsync
          - smartmontools
          - tmux
          - trash-cli
          - unzip
          - usbutils
          - zsh
          - wget
          - man-db
          - less
          - fd
          - gdu
          - bottom
      when: ansible_facts['distribution'] | lower == 'archlinux'


    - name: Install packages (Ubuntu)
      ansible.builtin.apt:
        name:
          - base
          - dhcpcd5
          - dosfstools
          - efibootmgr
          - git
          - grub-efi-amd64
          - vim
          - linux-generic
          - linux-headers-generic
          - linux-firmware
          - mtools
          - nano
          - os-prober
          - btop
          - curl
          - intel-microcode
          - mesa-utils
          - network-manager
          - net-tools
          - openssh-server
          - rsync
          - smartmontools
          - tmux
          - trash-cli
          - unzip
          - usbutils
          - zsh
          - python3-pip
      when: ansible_facts['distribution'] | lower == 'ubuntu'


    - name: Install AUR dependencies
      ansible.builtin.include_role:
        name: aur
      vars:
        state: latest
        packages:
          - downgrade
          - vim-plug
          - needrestart
      when: ansible_facts['distribution'] | lower == 'archlinux'

    - name: Install Ubuntu Dependencies
      ansible.builtin.apt:
        name:
          - vim
          - needrestart
        state: latest
        update_cache: true
      when: ansible_facts['distribution'] | lower == 'ubuntu'

  roles:
    - clamav
    - ssh
    - etckeeper
    - user
    - role: dotfiles
      vars:
        dotfiles_repo: https://github.com/brettinternet/dotfiles
        default_direnv_lines:
          - export KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
    - cockpit
    - kubecolor
