---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: homelab
  TIMEZONE: Europe/Paris

  NET_NODE_CIDR: "10.1.2.0/24"
  # Also defined in k3s provisioning setup
  NET_POD_CIDR: "10.42.0.0/16"
  NET_SVC_CIDR: "10.43.0.0/16"

  SVC_COREDNS_ADDR: 10.43.0.10
