---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-trakt-sync-config
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: plex-trakt-sync-dst
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
