# https://wiki.archlinux.org/title/ClamAV
---
- name: Install dependencies (Arch)
  ansible.builtin.package:
    state: latest
    name:
      - clamav
  when: ansible_facts['distribution'] | lower == 'archlinux'

- name: Install dependencies (Ubuntu)
  ansible.builtin.apt:
    name:
      - clamav
      - clamav-daemon
      - clamav-freshclam
      - fangfrisch
  when: ansible_facts['distribution'] | lower == 'ubuntu'

- name: Enable clamav daemon
  ansible.builtin.systemd:
    name: clamav-daemon.service
    enabled: true
    state: started

- name: Enable clamav definitions update
  ansible.builtin.systemd:
    name: clamav-freshclam.service
    enabled: true
    state: started

- name: Check Fangfrisch exists
  ansible.builtin.stat:
    path: /etc/fangfrisch/fangfrisch.conf
  register: fangfrisch_result

- block:
    - name: Install fangfrisch database repo (Arch)
      ansible.builtin.include_role:
        name: aur
      vars:
        state: latest
        packages:
          - python-fangfrisch
      when: ansible_facts['distribution'] | lower == 'archlinux'

    - name: Install fangfrisch database repo (Ubuntu)
      ansible.builtin.apt:
        name:
          - fangfrisch
      when: ansible_facts['distribution'] | lower == 'ubuntu'

    - name: Ensure Fangfrisch config directory exists
      ansible.builtin.file:
        path: /etc/fangfrisch
        state: directory
        owner: clamav
        group: clamav
        mode: '0755'

    - name: Create default Fangfrisch config file
      ansible.builtin.copy:
        dest: /etc/fangfrisch/fangfrisch.conf
        content: |
          [DEFAULT]
          db_url = sqlite:////var/lib/fangfrisch/db.sqlite
          local_directory = /var/lib/clamav
          [urlhaus]
          enabled = yes
        owner: clamav
        group: clamav
        mode: '0644'
      when: not fangfrisch_result.stat.exists

    - name: Create database structure
      become_user: clamav
      ansible.builtin.command: |-
        /usr/bin/fangfrisch --conf /etc/fangfrisch/fangfrisch.conf initdb
  when: not fangfrisch_result.stat.exists

- name: Enable clamav fangfrisch timer update
  ansible.builtin.systemd:
    name: fangfrisch.timer
    enabled: true
