apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:hDQa3o0N5zlHlyKoynAylK5MEVGPFKxEnivJGz8biAi7jMeUad87p30N8Rz3Z7+oOadEAm7Aoc/o7a75EKCiDxC0AGfXyDnhWXbCJj/f91qcuP1txg8o4vwwTPHUOZvDEg8bfogfzw+L7KQlGUERAjLHNP2jAa4bftQi/7z1HLKkV+Q+JF02M1Qs6REEa3tVkDsI5nM8RxWUkFxQdahrZ3J44AIRmK68rhglWdMsMsnxJXQpgLsQt6sjgIYJcffdq0RBExV1TUd5INmBHIoGcdGuSgDHXdoBF8fJfrBiGF9u7DFQ3GdUha6ZZL7KIEVLns5riLaL+sUC2KPCU7faUl68tr0HJX4TIepSsAGFP8X+0NtqEcSZ6JMHfIl1bLe/C2WcBB361XqeHWWYfl1186l0fEJ+DMdeeZLS6oS+AdTOCKjNIV8a9VjV+ZW95k20e6U/7hlmfzjP1iOnqVCHuv3nhfJAiOznO71JtxYanSEdryIKketrIdqDmKXjkUz0X+uEE3fQYh0YNVpPzsNCZi4ZEcbYQxfJC9IHRdlz+o7JcKFcX8s2Tgju9fcrY0T0QKyGA3fUPlNHjC74AVtXuiSFQBuCRwyU+UewyVgHoaCtlrT2zMPt+8JIgoGnnN/5P/hatUjbBYD+nG/WPRhRHRUaXRLCInkC81B+xn/+XMFb6bRDLDVZX39k+H4Kln9eEcGKxF91oclg8UDUmkUAW6YaKPAZ0kKWyl1rHT/r6d+e8LsbBn6KKKXe3MMYZeRt6g8OCLSJYE9r5YGAwxcPZWUhw0MJQx0oul9rRzY4qKyDQpYAC/7lpNQtVC4Rb5NdypRSuMqBf/KJ1h0iNbyAu11r18VYhvX1yr6YHo39oN6euRUPnqPp0pTz5U5QpzcXf0b8NYamfTYBBpE+rRr4f/IW4ojWbP+nTjI=,iv:hBdSwIggi5Mzg/WzzChkWhuTiI4A7Bq10OjFonJXiIw=,tag:NVUIVd/Uo6A+8eBw4fe1vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yfq0fyh2zthkacffmylwnaqdl79fu6273h5c5kpr4rcr5l8nrg5qdrd54u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlemJ1eWM5c3JPSW5HRVRP
            cTFsWG5qWHJaNmtpL0dOZTd5QXhYNGkwcFNrCkRkVDlPZmVEalZ0WE1DRFlmc2Ix
            b2c5STg0VXdGK0dXMjA2NVRoWk96V1kKLS0tIDhqRlVYUkxhb3RSTzRxbE90ZDUw
            SHRmQUZaZm5LNGxhaDZIUnl6VVFLZ2MKSlyK74Q2V0GmpDTJUGrXlQ/klUYnyosI
            DaapUKXYy3OJZWa3X5NZtSPz77TzyEDDPTloYjadpb5ZoBdN9WwUlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T13:50:56Z"
    mac: ENC[AES256_GCM,data:DhYA931KpU18Z9MhhlgNSyEnzH9zss5zCO3J9rG91kKbyRLZTpq9uhINM50bKufk2z2SiQoT0B6IClDTagmJ23QycAN1BN0HcphhXXz8fWGH+ELRRAGdyOJ76ASf/I7KofIDVor2XLVg8N1HRdyJSDwjraCkMhk5EGzkoH69j8M=,iv:WC0UAP/R1q5L3aE9gvc3VHIPietX10gy/XdYKU/i1ME=,tag:GJVLkxHsIJJeaAwyYOd+Xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
