---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: chart/tailscale-operator
      version: 0.1.0
      interval: 30m
      sourceRef:
        kind: GitRepository
        name: tailscale
        namespace: flux-system

  values:
