kind: ENC[AES256_GCM,data:y1nC137G,iv:RYdloHFESBr/HLEHswPD9Ljt7Cehb3ISekoy+HKcRDM=,tag:V84dEh3k6vbEWUREd26fUQ==,type:str]
ansible_user: ENC[AES256_GCM,data:OdBpqA==,iv:eZ7XTG6Po44G9j6BQ0bcWeeSfJIVRA9hQeRgiD+bJag=,tag:rVVi+mQt6kKZoLVfu/slJg==,type:str]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:PEXLfn1hRycpL9/gQML60lDg24+5BQDvXGs7,iv:3OGO05TwMFcIoM1XERCsr6DJX/rSfCW8tp/mc5pUkQw=,tag:ke6FJ0XaRDOvhIyIpFqgtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yfq0fyh2zthkacffmylwnaqdl79fu6273h5c5kpr4rcr5l8nrg5qdrd54u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTXUzN1N4ZFNka2lESVZG
            bVlXYXFQSC9sWm9oMEQ1UXNvUFNrN1ZaT0FBCkQ4VEdjOGNNSklZQVE5aXNKMG1B
            ZHE1Nlp3Mmk1L2c3SG5ETG5JNWRnajgKLS0tIHo0WDVZSEJaZEdZSEdqQ241NTdY
            Q29uaFB4MXNlVWhOQllpMHlkNTUzNnMKx2TSumMoqhlbzSnfJqNwXHVtCgiRMUzN
            /3KP80MFH84Dx4y0zFerMkx6uzm3WxRucGlWIysF+3bfdvukArM1bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-21T10:26:35Z"
    mac: ENC[AES256_GCM,data:dkQ1/TXJmYnOECe8kZjOnwr+UGYXDnHwpyVTg6im4r7DrQeTD7GF2CJ/6Qb+wmDnRV+fk6MVLrBC1AO+/gPA3iHR2HT8VcK6TgeyJLfrzjZA5L0/qeH/i37tFtCfXwKTa347GMAzl8xyC4ICxIHiG0tILLrmxz1eD8VpcBkK+X8=,iv:2FSWvJZ38FntgZyL7AkPH96v7alEuz8CrCbZ3RHLSmw=,tag:x56S66I9K8DkwlApuL4ulg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
